version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded_files:/app/uploaded_files
    depends_on:
      - chroma
    environment:
      - PYTHONUNBUFFERED=1

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"  # Chroma runs on 8000 inside container
    volumes:
      - chroma_data:/chroma/.chromadb

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  chroma_data:
  ollama_data:
